# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deef40b84ed3bd5ce0a0ecd354daf43e871bef0d9433c885422e9b35671d23c92f013b1c7fc7209adcb354f2ef992070249e2401b97ccd3592a1bc3c6405f473

test:
  secret_key_base: e90f83c3ba40a725bc02f932fcb1851673fe14b51548552540ff859e10691cced7dfd6588e12e03b9183cb684da89257223cdc22f18a83c094864810d35e8508

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
